Notice reports
wojdzie/refugee-help-board-backend pull request #7
Opened 2022-05-23 18:49 UTC by Neterpila

P.S. each commit has a description, so it's probably gonna be easier to go through them one by one

2022-06-06 07:55 UTC, wojdzie commented on app/notice/notice.controller.js
> +    const notice = (await noticeService.get({ _id: req.params.id}, true, true))[0];
Can you create a new service method to retrieve single element?

2022-06-06 07:58 UTC, wojdzie commented on app/report/report.service.js
> +			total: (await Notice.find({
You should avoid calling DB 4 times with similar requests in one function. Try to get all required data with single DB call.

2022-06-06 08:00 UTC, wojdzie requested changes
Please address identified issues

2022-06-06 08:00 UTC, wojdzie commented on app/report/report.service.js
> +		total: (await noticeService.get({}, true, true)).length,
Same thing as below

2022-06-07 10:12 UTC, Neterpila commented
Identified issues addressed, please review

2022-06-07 11:11 UTC, wojdzie approved these changes

2022-06-07 11:37 UTC, wojdzie approved these changes

2022-06-07 11:38 UTC, merged